# Generated by Django 5.1.3 on 2024-12-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NFL_weekly_view', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='MessageNW',
        ),
        migrations.RenameModel(
            old_name='Paid',
            new_name='PaidNW',
        ),
        migrations.RenameModel(
            old_name='Pick',
            new_name='PickNW',
        ),
        migrations.RenameModel(
            old_name='PromoCode',
            new_name='PromoCodeNW',
        ),
        migrations.RenameModel(
            old_name='PromoUser',
            new_name='PromoUserNW',
        ),
        migrations.RenameModel(
            old_name='Scorer',
            new_name='ScorerNW',
        ),
        migrations.RenameModel(
            old_name='Waitlist',
            new_name='WaitlistNW',
        ),
    ]
