# Generated by Django 5.1.3 on 2024-12-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFL_weekly_view', '0003_remove_picknw_isin'),
    ]

    operations = [
        migrations.AddField(
            model_name='picknw',
            name='pick_number',
            field=models.IntegerField(default=1),
        ),
    ]
