# Generated by Django 5.1.3 on 2024-12-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFL_weekly_view', '0005_alter_messagenw_id_alter_promocodenw_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagenw',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paidnw',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='picknw',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scorernw',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
    ]
