# Generated by Django 5.1.3 on 2024-12-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFL_weekly_view', '0006_messagenw_league_number_paidnw_league_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picknw',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
