# Generated by Django 5.1.4 on 2025-02-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NFL_weekly_view', '0007_picknw_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('group', models.CharField(default='username', max_length=100)),
            ],
        ),
    ]
