# Generated by Django 5.1.4 on 2025-01-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_SL', '0002_pastpickbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandSlam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='name', max_length=100)),
                ('player_ID', models.CharField(default='player ID', max_length=100)),
                ('username', models.CharField(default='username', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='scorerbl',
            old_name='touchdown_count',
            new_name='homerun_count',
        ),
        migrations.AddField(
            model_name='pickbl',
            name='isin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scorerbl',
            name='grand_slam',
            field=models.BooleanField(default=False),
        ),
    ]
