# Generated by Django 5.1.4 on 2025-01-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_SL', '0003_grandslam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandSlamBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='name', max_length=100)),
                ('player_ID', models.CharField(default='player ID', max_length=100)),
                ('username', models.CharField(default='username', max_length=100)),
                ('league_number', models.IntegerField(default=1)),
                ('teamnumber', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='GrandSlam',
        ),
    ]
