# Generated by Django 5.1.4 on 2025-01-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball_WL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorerbs',
            old_name='touchdown_count',
            new_name='homerun_count',
        ),
    ]
