# Generated by Django 5.1.3 on 2024-11-26 02:33

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseballPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='player name', max_length=100)),
                ('position', models.CharField(default='player position name', max_length=100)),
                ('team', models.CharField(default='player team name', max_length=100)),
                ('player_ID', models.CharField(default='player ID', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(default='Body')),
                ('author', models.CharField(default='Author', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.CharField(blank=True, default='Summary', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team_name', models.CharField(default='Team', max_length=100)),
                ('likes_count', models.IntegerField(default=0)),
                ('dislikes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(default='type a sport', max_length=100)),
                ('startDate', models.DateField(default=datetime.date.today)),
                ('endDate', models.DateField(default=datetime.date.today)),
                ('pot', models.CharField(default='1000', max_length=100)),
                ('week', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('week', models.IntegerField(blank=True, null=True)),
                ('is_header', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='player name', max_length=100)),
                ('position', models.CharField(default='player position name', max_length=100)),
                ('team_name', models.CharField(default='player team name', max_length=100)),
                ('player_ID', models.CharField(default='player ID', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('color', models.CharField(default='#000000', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('old', models.BooleanField(default=False)),
                ('young', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('your_primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='username', max_length=100)),
                ('paid_status', models.BooleanField(default=False)),
                ('numteams', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PastPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('team_name', models.CharField(default='Default Team Name', max_length=100)),
                ('teamnumber', models.IntegerField(default=1)),
                ('week', models.IntegerField(default=1)),
                ('pick1', models.CharField(default='N/A', max_length=100)),
                ('pick1_name', models.CharField(default='N/A', max_length=100)),
                ('pick2', models.CharField(default='N/A', max_length=100)),
                ('pick2_name', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('your_primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(default='Default Team Name', max_length=100)),
                ('teamnumber', models.IntegerField(default=1)),
                ('username', models.CharField(default='username', max_length=100)),
                ('email', models.EmailField(default='useremail@gamil.com', max_length=100)),
                ('isin', models.BooleanField(default=True)),
                ('pick1', models.CharField(default='N/A', max_length=100)),
                ('pick1_team', models.CharField(default='N/A', max_length=100)),
                ('pick1_position', models.CharField(default='N/A', max_length=100)),
                ('pick1_color', models.CharField(default='N/A', max_length=100)),
                ('pick1_player_ID', models.CharField(default='N/A', max_length=100)),
                ('pick1_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('pick2', models.CharField(default='N/A', max_length=100)),
                ('pick2_team', models.CharField(default='N/A', max_length=100)),
                ('pick2_position', models.CharField(default='N/A', max_length=100)),
                ('pick2_color', models.CharField(default='N/A', max_length=100)),
                ('pick2_player_ID', models.CharField(default='N/A', max_length=100)),
                ('pick2_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name of influencer', max_length=100)),
                ('code', models.CharField(default='Code', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PromoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('code', models.CharField(default='Code', max_length=100)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=100)),
                ('player_ID', models.CharField(default='player ID', max_length=100)),
                ('scored', models.BooleanField(default=False)),
                ('not_scored', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('first_name', models.CharField(default='first name', max_length=100)),
                ('last_name', models.CharField(default='last name', max_length=100)),
                ('dob', models.DateTimeField(default=django.utils.timezone.now)),
                ('verification_status', models.CharField(blank=True, max_length=20)),
                ('uuid', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='authentication.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'message')},
            },
        ),
    ]
