# Generated by Django 4.1.5 on 2023-12-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_savedplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('your_primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('isin', models.BooleanField()),
                ('week', models.IntegerField()),
                ('pcik1', models.CharField(max_length=100)),
                ('pcik2', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SavedPlayer',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
