# Generated by Django 5.1.3 on 2024-11-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_baseballplayer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseballplayer',
            old_name='team_name',
            new_name='team',
        ),
    ]
