# Generated by Django 4.1.5 on 2023-12-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_pick_delete_player_remove_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='pcik1',
            new_name='pick1',
        ),
        migrations.RenameField(
            model_name='pick',
            old_name='pcik2',
            new_name='pick2',
        ),
        migrations.AddField(
            model_name='pick',
            name='team_name',
            field=models.CharField(default='Default Team Name', max_length=100),
        ),
    ]
