# Generated by Django 4.1.5 on 2023-12-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_pick_isin_alter_pick_pick1_alter_pick_pick2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
