# Generated by Django 5.1.3 on 2024-12-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_pastpick_td1_count_pastpick_td2_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='paid',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pastpick',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pick',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scorer',
            name='league_number',
            field=models.IntegerField(default=1),
        ),
    ]
