# Generated by Django 4.1.5 on 2024-01-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_pick_pick1_alter_pick_pick2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='pick1',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='pick',
            name='pick2',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
