# Generated by Django 4.1.5 on 2024-01-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_pick_pick1_alter_pick_pick2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('your_primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='username', max_length=100)),
                ('paid_status', models.BooleanField(default=False)),
            ],
        ),
    ]
