# Generated by Django 4.1.5 on 2024-01-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='player name', max_length=100)),
                ('position', models.CharField(default='player position name', max_length=100)),
                ('team_name', models.CharField(default='player team name', max_length=100)),
                ('player_ID', models.CharField(default='player ID', max_length=100)),
            ],
        ),
    ]
