# Generated by Django 4.1.5 on 2024-01-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLPlayer',
            fields=[
                ('your_primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='player first name', max_length=100)),
                ('last_name', models.CharField(default='player last name', max_length=100)),
                ('position', models.CharField(default='player position name', max_length=100)),
                ('team_name', models.CharField(default='player team name', max_length=100)),
                ('player_ID', models.CharField(default='player ID', max_length=100)),
            ],
        ),
    ]
