# Generated by Django 4.1.5 on 2024-01-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_nflplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflplayer',
            name='your_primary_key',
        ),
        migrations.AddField(
            model_name='nflplayer',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
