# Generated by Django 5.1.4 on 2025-01-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
