# Generated by Django 5.1.4 on 2025-01-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_group_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseballplayer',
            name='color',
            field=models.CharField(default='#000000', max_length=100),
        ),
    ]
