# Generated by Django 4.1.5 on 2024-01-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflplayer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
