# Generated by Django 4.1.5 on 2024-01-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_nflplayer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflplayer',
            name='color',
            field=models.CharField(default='#000000', max_length=100),
        ),
    ]
