# Generated by Django 5.1.4 on 2025-02-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_kyc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='pick1',
            new_name='pick',
        ),
        migrations.RenameField(
            model_name='pick',
            old_name='pick1_color',
            new_name='pick_color',
        ),
        migrations.RenameField(
            model_name='pick',
            old_name='pick1_player_ID',
            new_name='pick_player_ID',
        ),
        migrations.RenameField(
            model_name='pick',
            old_name='pick1_position',
            new_name='pick_position',
        ),
        migrations.RenameField(
            model_name='pick',
            old_name='pick1_team',
            new_name='pick_team',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='pick1_image',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='pick2',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='pick2_color',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='pick2_image',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='pick2_player_ID',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='pick2_position',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='pick2_team',
        ),
        migrations.AddField(
            model_name='pick',
            name='pick_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pick',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
