# Generated by Django 5.1.4 on 2025-02-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_rename_pick1_pick_pick_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='email', max_length=100)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
    ]
