# Generated by Django 4.1.5 on 2024-02-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='name',
            field=models.CharField(default='type a sport', max_length=100),
        ),
    ]
