# Generated by Django 4.1.5 on 2024-02-13 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_date_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date',
            old_name='name',
            new_name='sport',
        ),
    ]
