# Generated by Django 4.1.5 on 2024-02-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_rename_name_date_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='numteams',
            field=models.IntegerField(default=1),
        ),
    ]
