# Generated by Django 5.1.4 on 2025-02-11 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_alter_wallet_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
    ]
