# Generated by Django 4.1.5 on 2024-02-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_paid_numteams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='numteams',
            field=models.IntegerField(default=0),
        ),
    ]
