# Generated by Django 4.1.5 on 2024-02-15 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_paid_numteams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pick',
            old_name='week',
            new_name='teamnumber',
        ),
    ]
