# Generated by Django 5.1.4 on 2025-02-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_rename_amount_wallet_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='balance',
            new_name='amount',
        ),
    ]
