# Generated by Django 4.1.5 on 2024-02-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_rename_week_pick_teamnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='pick1_position',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='pick',
            name='pick1_team',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='pick',
            name='pick2_position',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='pick',
            name='pick2_team',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
