# Generated by Django 5.1.4 on 2025-02-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_rename_balance_wallet_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='email',
            new_name='group',
        ),
    ]
