# Generated by Django 4.1.5 on 2024-02-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_pick_pick1_position_pick_pick1_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='pick1_color',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='pick',
            name='pick1_player_ID',
            field=models.CharField(default='player ID', max_length=100),
        ),
        migrations.AddField(
            model_name='pick',
            name='pick2_color',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='pick',
            name='pick2_player_ID',
            field=models.CharField(default='player ID', max_length=100),
        ),
    ]
