# Generated by Django 4.1.5 on 2024-02-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_pick_pick1_color_pick_pick1_player_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('team_name', models.CharField(default='Default Team Name', max_length=100)),
                ('pick1', models.CharField(default='N/A', max_length=100)),
                ('pick2', models.CharField(default='N/A', max_length=100)),
                ('pick3', models.CharField(default='N/A', max_length=100)),
                ('pick4', models.CharField(default='N/A', max_length=100)),
                ('pick5', models.CharField(default='N/A', max_length=100)),
                ('pick6', models.CharField(default='N/A', max_length=100)),
                ('pick7', models.CharField(default='N/A', max_length=100)),
                ('pick8', models.CharField(default='N/A', max_length=100)),
                ('pick9', models.CharField(default='N/A', max_length=100)),
                ('pick10', models.CharField(default='N/A', max_length=100)),
                ('pick11', models.CharField(default='N/A', max_length=100)),
                ('pick12', models.CharField(default='N/A', max_length=100)),
                ('pick13', models.CharField(default='N/A', max_length=100)),
                ('pick14', models.CharField(default='N/A', max_length=100)),
                ('pick15', models.CharField(default='N/A', max_length=100)),
                ('pick16', models.CharField(default='N/A', max_length=100)),
                ('pick17', models.CharField(default='N/A', max_length=100)),
                ('pick18', models.CharField(default='N/A', max_length=100)),
                ('pick19', models.CharField(default='N/A', max_length=100)),
                ('pick20', models.CharField(default='N/A', max_length=100)),
                ('pick21', models.CharField(default='N/A', max_length=100)),
                ('pick22', models.CharField(default='N/A', max_length=100)),
                ('pick23', models.CharField(default='N/A', max_length=100)),
                ('pick24', models.CharField(default='N/A', max_length=100)),
                ('pick25', models.CharField(default='N/A', max_length=100)),
                ('pick26', models.CharField(default='N/A', max_length=100)),
                ('pick27', models.CharField(default='N/A', max_length=100)),
                ('pick28', models.CharField(default='N/A', max_length=100)),
                ('pick29', models.CharField(default='N/A', max_length=100)),
                ('pick30', models.CharField(default='N/A', max_length=100)),
                ('pick31', models.CharField(default='N/A', max_length=100)),
                ('pick32', models.CharField(default='N/A', max_length=100)),
                ('pick33', models.CharField(default='N/A', max_length=100)),
                ('pick34', models.CharField(default='N/A', max_length=100)),
                ('pick35', models.CharField(default='N/A', max_length=100)),
                ('pick36', models.CharField(default='N/A', max_length=100)),
                ('pick37', models.CharField(default='N/A', max_length=100)),
                ('pick38', models.CharField(default='N/A', max_length=100)),
                ('pick39', models.CharField(default='N/A', max_length=100)),
                ('pick40', models.CharField(default='N/A', max_length=100)),
                ('pick41', models.CharField(default='N/A', max_length=100)),
                ('pick42', models.CharField(default='N/A', max_length=100)),
                ('pick43', models.CharField(default='N/A', max_length=100)),
                ('pick44', models.CharField(default='N/A', max_length=100)),
                ('pick45', models.CharField(default='N/A', max_length=100)),
                ('pick46', models.CharField(default='N/A', max_length=100)),
                ('pick47', models.CharField(default='N/A', max_length=100)),
                ('pick48', models.CharField(default='N/A', max_length=100)),
                ('pick49', models.CharField(default='N/A', max_length=100)),
                ('pick50', models.CharField(default='N/A', max_length=100)),
                ('pick51', models.CharField(default='N/A', max_length=100)),
                ('pick52', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_ID', models.CharField(default='player ID', max_length=100)),
            ],
        ),
    ]
