# Generated by Django 4.1.5 on 2024-02-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_pastpick_scorer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastpick',
            name='teamnumber',
            field=models.IntegerField(default=1),
        ),
    ]
