# Generated by Django 4.1.5 on 2024-04-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_promocode_promouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='paid',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
