# Generated by Django 4.1.5 on 2024-04-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_paid_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pot',
            field=models.CharField(default='1000', max_length=100),
        ),
    ]
