# Generated by Django 4.1.5 on 2024-04-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_alter_game_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='pick1_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pick',
            name='pick2_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
