# Generated by Django 4.1.5 on 2024-05-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_ofage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=2)),
                ('dob_day', models.IntegerField()),
                ('dob_month', models.IntegerField()),
                ('dob_year', models.IntegerField()),
                ('verification_status', models.CharField(blank=True, max_length=20)),
                ('uuid', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
