# Generated by Django 4.1.5 on 2024-05-07 00:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_userverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userverification',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='dob_day',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='dob_month',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='dob_year',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userverification',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='userverification',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
