# Generated by Django 4.1.5 on 2024-05-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_remove_userverification_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='first_name',
            field=models.CharField(default='first name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userverification',
            name='last_name',
            field=models.CharField(default='last name', max_length=100),
        ),
    ]
