# Generated by Django 4.1.5 on 2024-05-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_alter_userverification_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofage',
            old_name='status',
            new_name='old',
        ),
        migrations.AddField(
            model_name='ofage',
            name='young',
            field=models.BooleanField(default=False),
        ),
    ]
