# Generated by Django 4.1.5 on 2024-05-22 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0037_rename_status_ofage_old_ofage_young'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('body', models.TextField(default='Body')),
                ('author', models.CharField(default='Author', max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('summary', models.CharField(blank=True, default='Summary', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
