# Generated by Django 5.0.6 on 2024-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0040_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
