# Generated by Django 5.0.6 on 2024-06-05 22:51

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_chatmessage_dislikes_chatmessage_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(default='Body'),
        ),
    ]
