# Generated by Django 5.0.6 on 2024-05-29 05:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0041_chatmessage_dislikes_chatmessage_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Body'),
        ),
    ]
