# Generated by Django 5.0.6 on 2024-10-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0043_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorer',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AddField(
            model_name='scorer',
            name='scored',
            field=models.BooleanField(default=True),
        ),
    ]
