# Generated by Django 5.0.6 on 2024-10-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0044_scorer_name_scorer_scored'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorer',
            name='not_scored',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pick',
            name='pick1_player_ID',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='pick',
            name='pick2_player_ID',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='scorer',
            name='scored',
            field=models.BooleanField(default=False),
        ),
    ]
